### ISSUE TITLE
ATP Manual Trigger Messaging - Update alternate phase message (TFS 37730)

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#106]
From John Still:

Need to update the text below to include letting the user know that the process of starting the alternate phase will take up to 10 minutes to complete and they will see a success banner on their screen when the alternate phase has begun.  

Step 2 of 3: Start alternate phase

During this phase hiring managers will continue to review applicants for their internship opportunity and make their alternate selections.  If they haven’t filled all of their primary slots, they can also complete their primary selections.

**Comment by dalenard21** [comment]
@Piglady64 see the request above. Can you please review this revised content for the alternate phase message?

**Step 2 of 3: Start alternate phase**
During this phase hiring managers will continue to review applicants for their internship opportunity and make their alternate selections.  If they haven’t filled all of their primary slots, they can also complete their primary selections. 

It may take up to 10 minutes for the boards to repopulate for the alternate phase. Once the boards are ready, you’ll see a success banner at the top of the screen.

**Comment by Piglady64** [comment]
@dalenard21 This look good. I am assuming this is the message when Khadijah starts alternate phase.

**Comment by dalenard21** [comment]
@Piglady64 yes, this is the message she will see when she comes into ATP to start the alternate phase.  So, it will update the text on this screen:


https://opm.invisionapp.com/d/main#/console/17190930/360656827/preview

I assume it will update the 'alternate phase' text wherever it appears.

@jdstill please use this content:

Step 2 of 3: Start alternate phase
During this phase hiring managers will continue to review applicants for their internship opportunity and make their alternate selections. If they haven’t filled all of their primary slots, they can also complete their primary selections.

It may take up to 10 minutes for the boards to repopulate for the alternate phase. Once the boards are ready, you’ll see a success banner at the top of the screen.

**Comment by jdstill** [comment]
Thanks

**Comment by dalenard21** [comment]
@jdstill has updated the TFS ticket with the revised content.  Closing this issue.
