### ISSUE TITLE
Baseurl not working

### ISSUE THREAD

**Issue by eponsonby** [USAJOBS/ATP-Support#129]
Having an issue with the baseurl in the _config.yml file. Currently experiencing this issue in production. When you go to https://usajobs.github.io/ATP-Support/ and click on any of navigation links, it takes you to https://usajobs.github.io/campaigns/ for example, instead of https://usajobs.github.io/ATP-Support/campaigns/ which displays a 404 error

**Comment by SeanKilleen** [comment]
@jonwoody @eponsonby realizing that I shouldn't have closed this with #130. Sorry! You may want to reopen. The PR was meant to support it and was not a guaranteed fix.
