### ISSUE TITLE
Open Opps Help: Create new search section and add new page

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#14]
We need to add a page to the Open Opps help center for "filters".

The page will be: How to use the filters.

It should live in a new help section called "Search".

1. Create a new section/tab called Search
2. Add a link to the page "How to use the filters" (or something like that).
3. Debbie will create the content for the how to use the filters page.
4. Provide the URL for "How to use filters" to the open opps dev team so they can link the help icon that's in the filters section of open opps.

**Comment by humancompanion** [comment]
This is the wrong repo for this. I think I gave the wrong URL. Sorry! I moved it to the correct locale: https://github.com/USAJOBS/openopps-help/issues/2
