### ISSUE TITLE
JOA playbook: Clarify when to use internal to an agency

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#15]
There is a thread in #support-questions where an agency was confused about when to use internal to an agency:

```
. I trained our HR staff yesterday. There were several offices that open announcements to Department of Transportation employees, not just FAA. They asked which hiring path would they include.

My initial thought is to select "federal employees - competitive service" and also "federal employees- excepted service"; however, the text under federal employees states current or former competitive service federal employees. In our scenario, FAA does not allow "former" federal to apply so it is misleading.

My other thought is to use "internal to an agency"; however, it is really internal to a "department". Is there any thoughts on a "Department" icon?

Can you provide guidance on which hiring path we should use?
```

The answer from @danthibodeau was "internal, they should use clarifying text to say all DoT employees can apply...using either federal option would appears as though all federal employees can apply". @dpboyd asked if we could make that clearer in the playbook.

**Comment by dalenard21** [comment]
this was updated.

https://usajobs.github.io/ATP-Support/job-announcement-playbook/details/this-job-is-open-to/

closing issue.
