### ISSUE TITLE
JOA Playbook: Add video field

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#16]
We've added a distinct video field to the JOA. We need to let folks know about this in the playbook. I need to figure out which section this is attached to, if any.

Note that there is a bug here where an empty video drawer shows up for the field on mobile even when there is no content. It's currently on the backlog. We could mention that we know about it and plan to fix it....soon.

**Comment by dalenard21** [comment]
Sent draft guidelines to Julie, Dan and John.  Included feedback from Julie.  Dan had no updates. Waiting to hear back from John.

FYI, here's an example of the type of video that could appear in the field.

https://www.youtube.com/watch?v=iP-dgprNGnw

At 9 minutes, this is too long. We're suggesting no more than two minutes. 90 is ideal (based on some research).  You can post up to two videos.

**Comment by dalenard21** [comment]
@starrchen here's the video field 'file' in github
https://github.com/USAJOBS/ATP-Support/blob/master/job-announcement-playbook/details/video.md

I'm not sure how to check if the page shows the correct navigation. It should appear just after 'Location" and before "Duties" in the playbook.

https://usajobs.github.io/ATP-Support/job-announcement-playbook/details/

Check with Matt about where this gets pushed. I think we can push straight to production, but I'm not 100% sure.

**Comment by dpboyd** [comment]
Thanks Deb!

On Oct 16, 2018, at 12:46 PM, dalenard21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Sent draft guidelines to Julie, Dan and John. Included feedback from Julie. Dan had no updates. Waiting to hear back from John.

FYI, here's an example of the type of video that could appear in the field.

https://www.youtube.com/watch?v=iP-dgprNGnw

At 9 minutes, this is too long. We're suggesting no more than two minutes. 90 is ideal (based on some research). You can post up to two videos.

-

**Comment by dalenard21** [comment]
The video field guidelines are now in production:
https://usajobs.github.io/ATP-Support/job-announcement-playbook/details/video/

Thanks @starrchen 

Issue closed.
