### ISSUE TITLE
Consolidate dual login screens [TFS 30976]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#17]
@dreeeeewwwww commented on [Wed Oct 03 2018](https://github.com/USAJOBS/team-polydeuces/issues/246)

![img_5483_](https://user-images.githubusercontent.com/13023132/46439723-4a601000-c72f-11e8-800a-1b595f7172f3.jpg)
From TFS:
- Brand like USAJOBS.
- Differentiate from core login.

- Two options exist for logging in but perform the same action.
- `Continue with staffing` directs to inaccurate PIV card image, if PIV card image is used make it correct.
 - Build login page with PIV img OR login fields (ex: Facebook's login with img OR email/pass)

Questions and [Updates] from Matt:

- Can we combine PIV/CAC login? [Marshall says yes]
- Marshall says USAS may be using the same PIV service. Today it's not shared.
- Michelle has asked us to sync up with USAS.
- To register their PIV they have to login first with username and password. We don't tell them this.

**Comment by humancompanion** [comment]
From Pete B's write up it seems that ATP and USAS are not yet using the same PIV service. So these designs are not optimal. We'll need to retain having folks pick USAJOBS or USA Staffing and have PIV for both specific to those options. Do your best to bring clarity to this unfortunate situation.

**Comment by dreeeeewwwww** [comment]
A few sketches to look over at today's 5pm meeting:

![atp-login-1](https://user-images.githubusercontent.com/13023132/46695408-7b33bf80-cbdd-11e8-9b1f-71dd727bd67b.png)
![atp-login-2](https://user-images.githubusercontent.com/13023132/46695409-7b33bf80-cbdd-11e8-9e06-9a5d7f2f74ba.png)
![atp-login-3](https://user-images.githubusercontent.com/13023132/46695410-7b33bf80-cbdd-11e8-994a-bb1460dc485f.png)

**Comment by humancompanion** [comment]
I like variation 4 but it would also need to offer PIV card sign in.

**Comment by dreeeeewwwww** [comment]
- [ ] consider alert locations

**Comment by dreeeeewwwww** [comment]
> I like variation 4 but it would also need to offer PIV card sign in.

Yeah totally. I was thinking we could add as many login types as we need in the left list.

**Comment by humancompanion** [comment]
Another todo to add to your checklist is Explain to user what the difference between USAJ & USAS means here and why we are asking. Right now we just assume they know the difference, which they may not. 

For USAS that would be - do you have an account already with USA Staffing? (Or perhaps "Are you an HR Specialist or Hiring Manager who uses USA Staffing?"). For USAJ I'd get help from Lauren on how to explain it. 

Variation 3 could work as well if it was a bit more like variation 4 where it exposed something underneath. The catch here is that 1. The PIV card for USAJ isn't yet desired, though possible and 2. There are still two different types of providers for both PIV and Email and Password auth. Thus you have to select which you want to use first (USAJ vs. USAS), then the method (PIV vs. Email/Pwd).

**Comment by dreeeeewwwww** [comment]
@humancompanion I have some of the symbols working as libraries so it's still heavily sketchy here ...

Is something like this an allowable use of the help drawer (it is outside of the normal text field/form context here)?

![atp-login-with-help-drawer](https://user-images.githubusercontent.com/13023132/46765527-3a0ae080-ccad-11e8-8924-9c1ff3c9ae82.png)

**Comment by humancompanion** [comment]
I don't think this is the best use of the help drawer because I suspect users should see this associated more closely with each sign in option and exposed because hiding it, while it does clean up the page a bit, kinda keeps it away when it would be most useful. 

At the risk of card-itis I'd suggest the buttons be turned into "cards" with the brief explanations below the title and a button to sign in using that option. 

Also, the PIV/CAC has to be after they choose which mechanism because the PIV services are not yet shared. A couple of things to note around this:

1. To register their PIV they have to login first with username and password. We don't tell them this. We should.
2. Brody has filed (or will) a waiver to remove password requirement, activity requirement, etc. We said we'd create designs for both waiver being signed and not. @abudz19 is going to get the waiver info from Brody. For tomorrow let's focus on the waiver not being signed version. In which case, PIV/CAC has to happen after they choose an account to sign in with because the PIV services are not yet shared.

**Comment by abudz19** [comment]
@humancompanion @dreeeeewwwww 

The waiver if approved will remove password requirements (length, special characters, etc.) to be in line with NIST standards and should not affect the design. The waiver will also remove for all users the automatic lockout for those who have not signed in for 35 days (backend process) and should not affect the design. There is also no estimable timeline for when the waiver can/will be approved.

**Comment by humancompanion** [comment]
Thanks @abudz19. Okay, so it does not impact this design but does impact issue #19 which I just grabbed. On it!

**Comment by dreeeeewwwww** [comment]
@humancompanion Is this more in the right direction? 

I copied from the Card Button style and used some placeholder icons and descriptive text. Swapped the "sign in" button text to "continue" thinking that might be less confusing to be directed to _another_ sign in page after clicking `sign in`.

![atp-login-card](https://user-images.githubusercontent.com/13023132/46834335-275ddd80-cd79-11e8-9d3b-590ed0b295f0.png)

**Comment by dreeeeewwwww** [comment]
Moving forward with a new layout for this on a local branch, working off Matt's other additions to the `/auth` dir for forgot/reset password.

**Comment by dreeeeewwwww** [comment]
@dalenard21 Here's a couple items we need help with copy for (copying this over from Slack):

- [ ] Underneath the `Sign in` h1, something to help direct you to choose either USAJOBS or USA Staffing
- [] Some text for both options that explain who might sign in with each and what will happen when you continue

**Comment by abudz19** [comment]
@dreeeeewwwww I cc'd you on the email exchange I had with Pete. When they try to sign-in with their PIV card and it has not been registered before, it brings them to this screen: 

![sign in to register your smart card](https://user-images.githubusercontent.com/11526811/46883675-d1447500-ce20-11e8-875a-4fed13fa5159.jpg)

They do not indicate this step ahead of time.

**Comment by dreeeeewwwww** [comment]
@abudz19 That's a tricky part of the process we def need help putting into words, I forgot to add that to the above copy help checklist. Do you have a concept of how we might best convey that?

**Comment by abudz19** [comment]
@dreeeeewwwww @dalenard21 

Can we give them a similar screen as Staffing, and then just say something like:
**Register your PIV card**
By signing in below, your PIV card will be authenticated and available for future sign-in.

Alternately, as Matt said before, we can choose to do nothing since USAS does not alert their customers either.

**Comment by humancompanion** [comment]
![screenshot 2018-09-27 13 37 25](https://user-images.githubusercontent.com/352987/46892254-cc8cba80-ce3a-11e8-8fa4-6cebb9208e87.png)

Let's use USAS' "Sign in with PIV/CAC"

**Comment by humancompanion** [comment]
![screenshot 2018-09-27 13 33 49](https://user-images.githubusercontent.com/352987/46892296-e8905c00-ce3a-11e8-87e3-e16f2f782a08.png)

Existing USAJOBS page for reference.

**Comment by dreeeeewwwww** [comment]
@humancompanion Opened a pull request with the majority of the changes we talked about earlier, _but ..._

I'm struggling with getting the USAJ and USAS logo images to work in the Button Card element without throwing the text totally off. Will address that in the morning Monday.

**Comment by humancompanion** [comment]
This experience starts here:
https://usajobs.github.io/design-system/agency-talent-portal/auth/sign-in/

**Comment by humancompanion** [comment]
@dreeeeewwwww to make the last updates in here and then close this out today.

**Comment by dreeeeewwwww** [comment]
Notes for the entire updated ATP login process for TFS ticket creation:

-----

# ATP Login


## 01 Sign in
**https://usajobs.github.io/design-system/agency-talent-portal/auth/sign-in/**

- Radio select to log user into ATP with either USAJOBS or USAS account.
 - Logos and descriptive text for each radio option.
 - Selected option turns green, consistent with Card Button component.
 - USAJOBS selection directs to `02 Sign in USAJOBS` [below].
 - USAS selection directs to USA Staffing login.
- USAJOBS terms and conditions linked at bottom.


## 02 Sign in USAJOBS
**https://usajobs.github.io/design-system/agency-talent-portal/auth/sign-in-usajobs/**

- Sign in with USAJOBS email and password ... _or_ ...
- Sign in with PIV card by clicking on Font Awesome badge icon.
 - Descriptive text for first-time PIV sign-in process.
- Link to USAJOBS terms and conditions.
- Link to Forgot Password page.
- Contact `mailto:` for creating new account.


## 03 Forgot password

### Enter email
**https://usajobs.github.io/design-system/agency-talent-portal/auth/forgot-password/**

- Enter email to reset password.
- Link to cancel and return home.

### Email sent
**https://usajobs.github.io/design-system/agency-talent-portal/auth/check-email/**

- Confirmation with user's email highlighted in bold.
- Option to click `resend` in case first message didn't go through.

### Responsive email template
**https://federalist-proxy.app.cloud.gov/site/usajobs/responsive-emails/atp-reset-password.html**

- Standard responsive email.
- Large reset password button.
- Additional reset password link exposing full reset url.
- Link to ATP Support page.

### Reset password
**https://usajobs.github.io/design-system/agency-talent-portal/auth/reset-password/**

- Input for new password.
- Extended contextual help box details password requirements.

### Reset success
**https://usajobs.github.io/design-system/agency-talent-portal/auth/sign-in-with-success/**

- Affirmative alert confirming successful password reset.
- Same login screen/options from [02 Sign in USAJOBS] above.


## 04 Signed out
**https://usajobs.github.io/design-system/agency-talent-portal/session/signed-out/**

- Copied from standard USAJOBS sign out page.
- Sign out text edited to match ATP, "YOU ARE NOW SIGNED OUT. THANKS FOR USING USAJOBS AGENCY TALENT PORTAL."
- Link to FAQ.
