### ISSUE TITLE
Set password page - Update page design [TFS 31373]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#18]
Talk to Dwayne on how this works today. Is there a way to edit it from the default?

**Comment by abudz19** [comment]
@dreeeeewwwww 
Acceptance criteria from the TFS ticket

- The set new password page utilizes the USAJOBS Design System
- The password requirements do not overlap with other page elements, including the footer.

**Comment by humancompanion** [comment]
Ah ha. This is done. Didn't need to be a distinct ticket.

https://usajobs.github.io/design-system/agency-talent-portal/auth/reset-password/
