### ISSUE TITLE
Password reset page/Forgot password page - Update page design [TFS 31390 & 35052]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#19]
<img width="1680" alt="screen shot 2018-10-09 at 5 20 09 pm" src="https://user-images.githubusercontent.com/13023132/46699442-d074ce80-cbe7-11e8-8683-f3beb0453688.png">
<img width="1680" alt="screen shot 2018-10-09 at 5 22 53 pm" src="https://user-images.githubusercontent.com/13023132/46699492-fef2a980-cbe7-11e8-9045-fdf131eb06ed.png">
<img width="1680" alt="screen shot 2018-10-09 at 5 23 18 pm" src="https://user-images.githubusercontent.com/13023132/46699710-9bb54700-cbe8-11e8-8898-30ff75b7d705.png">

Restrictions:
- you HAVE to be logged out to reset your password.

**Comment by humancompanion** [comment]
@starrchen for this issue we'll need a responsive email. Please create a new email using the template here: https://github.com/USAJOBS/responsive-emails/blob/master/src/pages/auth-update-your-gov-email-address.html

@dalenard21 - We could use your help with the content. We should base it on the login.gov email which I have attached below:

![screenshot 2018-10-11 16 27 32](https://user-images.githubusercontent.com/352987/46832233-86205880-cd73-11e8-8e91-2e2055fbb10c.png)

Starr - For now use this content and just change the login.gov mentions to usajobs.gov. Thanks!

**Comment by abudz19** [comment]
[Link to TFS Ticket 31390](https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Polydeuces/_workitems?id=31390&_a=edit)
[Link to TFS Ticket 35052](https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Polydeuces/_workitems?id=35052&_a=edit)

**Comment by humancompanion** [comment]
Forgot password: https://usajobs.github.io/design-system/agency-talent-portal/auth/forgot-password/
Reset password: https://usajobs.github.io/design-system/agency-talent-portal/auth/reset-password/

Responsive email (HTML): https://federalist-proxy.app.cloud.gov/site/usajobs/responsive-emails/atp-reset-password.html
Responsive email (Txt): https://federalist-proxy.app.cloud.gov/site/usajobs/responsive-emails/atp-reset-password.txt
