### ISSUE TITLE
Sign out page - update page design [TFS 29707]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#20]
Use a consistent sign out page that is similar to Core but with different content.

- [x] Copy design system sign out pages
- [x] Update text "thanks for using `USAJOBS Agency Talent Portal`"
- [x] Point links to correct locations
- [x] Update design system with new layout
- [x] Create new path - nest under Layouts/Agency Talent Portal/Session/

**Comment by dreeeeewwwww** [comment]
Have a local branch for this going now, will be copying over/editing the existing sign out page and sending a pull request later today.

**Comment by dalenard21** [comment]
@dreeeeewwwww @starrchen 

Here's some copy to use for the signed out page.

[ATP-sign-out_20181010.docx](https://github.com/USAJOBS/ATP-Support/files/2469360/ATP-sign-out_20181010.docx)

This hasn't been approved by Brody, but I worked with Julie and Lauren on the language.  

One question - where will the "Sign in again" link go?

**Comment by dreeeeewwwww** [comment]
@humancompanion @starrchen Creating a pull request for this now. There wasn't too much content in the word doc so I just went ahead and added it. Easy for any of us to update in case that content changes though.

**Comment by humancompanion** [comment]
Page can be found at: 
https://usajobs.github.io/design-system/agency-talent-portal/session/signed-out-atp/

**Comment by abudz19** [comment]
[Link to TFS Ticket 29707](https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workItems?_a=edit&id=29707&triage=false)
