### ISSUE TITLE
Manage users - user status alerts[TFS 31790]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#21]
- When editing a user you manage, separate the kinds of alerts you get about given user.
- Edit color codes for types alerts?

<img width="1680" alt="screen shot 2018-10-09 at 5 42 40 pm" src="https://user-images.githubusercontent.com/13023132/46700526-09fb0900-cbeb-11e8-9063-e3bc49d646eb.png">
<img width="1680" alt="screen shot 2018-10-09 at 5 43 31 pm" src="https://user-images.githubusercontent.com/13023132/46700529-0b2c3600-cbeb-11e8-9044-e03b0bc03822.png">

**Comment by abudz19** [comment]
From the TFS Ticket

The Manage Users page is modified to have two tabs:
Enabled: lists all users who do not have a disabled account
Disabled: lists users who have a disabled account
If password expire, locked out, disabled, inactive, expiration date.

This ticket does not address the "Reactivate Button" (35095)

Deviations from the mockup:

- Active is relabeled "Enabled"
- Inactive is relabeled "Disabled"

Mockups attached

**Comment by humancompanion** [comment]
Active: https://opm.invisionapp.com/d/main/#/console/10214303/237208487/preview
Inactive: https://opm.invisionapp.com/d/main/#/console/10214303/237208484/preview

**Comment by humancompanion** [comment]
I wired up those screens in InVision. This should be sufficient for this iteration.
