### ISSUE TITLE
Clarify language for PIV sign in

### ISSUE THREAD

**Issue by starrchen** [USAJOBS/ATP-Support#28]
It was requested that we make the language around the PIV log in more clear, as users may not understand that they need to use email and password when they first register the cert with their card.

![image.png](https://images.zenhubusercontent.com/5ba2602c3fd1d02b91c1adbd/c28ef004-cc5f-4b65-b821-c0d5f21fa56b)

From the TFS ticket:
>When clicking on the PIV icon:
If the user selects a PIV certificate that is not registered to an account, they will then be prompted to associate the certificate with an account.
If the certificate has already been associated with an account, the user will be prompted for a PIN.
If the certificate has not been associated with an account, the user can then register the selected certificate with their account by providing their email address and password (as is done now).

>Mock deviations:
"First time signing in?" is changed to "Need to register your PIV?"
The PIV language is changed from "Register your PIV card by first signing in with your email and password." to "Register your PIV card and associate it with your account."
All references to "USAJOBS account" are changed to "USAJOBS recruiter account"

**Comment by dalenard21** [comment]
Hi @starrchen 

What email and password do they need to use to sign in?  Their USAJOBS email address and password?

**Comment by dalenard21** [comment]
@starrchen I'll get you updated content tomorrow.

**Comment by dalenard21** [comment]
@starrchen @dreeeeewwwww 

Here's another attempt at the language for this screen: https://usajobs.github.io/design-system/agency-talent-portal/auth/sign-in-usajobs/

1. Update the intro language to say:

Sign in using your USAJOBS recruiter account.

2. Update the "Need to create an account" language to say:

Need an account? Contact your agency administrator or email recruiter-help@usajobs.gov.

3. Remove the "First time signing in" language from the PIV card.  Instead, if a user clicks on the PIV card option, we'll present them with a message asking them to sign in using their email and password.  

Use this message:
Before you can use your PIV card to sign in, you need to first sign in using your USAJOBS recruiter account email and password.  We'll then automatically link your PIV card so you can use it next time.
