### ISSUE TITLE
Clarify validation states and language on reset password page [TFS 35276]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#30]
**Reset password page**
https://usajobs.github.io/design-system/agency-talent-portal/auth/reset-password/

**Design System validation**
https://usajobs.github.io/design-system/form-controls/#validation

**Your password must:**
- [x] **Not match your username**
- [x] **Not to be a recently used password**
- [x] **Be 8 to 20 characters long**
- [x] **Have at least one upper case letter**
- [x] **Have at least one lower case letter**
- [x] **Have at least one number**
- [x] **Missing valid symbol**
"Must not include any symbol other than ! @ # $ % ^ & * ( )"
- [x] **Invalid symbol entered**
"Must not include any symbol other than ! @ # $ % ^ & * ( )"

**Quick mock-up**
- [x] Screengrab of single error
- [x] Screengrab of multiple errors

**Comment by dreeeeewwwww** [comment]
@dalenard21 I took a quick stab at some copy for the error states, am mostly just regurgitating the statement from the help box. 

Any input/updates/etc would be great.

**Comment by dalenard21** [comment]
Hi @dreeeeewwwww 

Will we show each error separately or as a list?  I thought we'd just repeat the language we currently have and just make it red or green depending on what they enter.

Can we show them as they go?  Or do we have to wait until we hit submit?

For example, we can show the 'errors' as a list:

Your password must:
* Be 8 - 20 characters long.
* Include at least one number.
* Not be a recently used password.
* Not match your username. (OR Not be the same as your username - either one works)

For the invalid symbol one, we can reword to:

* Must not include any symbol other than ! @ # $ % ^ & * ( )

Thoughts?

**Comment by dreeeeewwwww** [comment]
Good idea on the list. I was thinking it would be a sentence when there is just one error and a list when there were multiple ... but that is creating two things that achieve the same goal ... might as well have them any/all errors display as a list to begin with.

**Comment by dreeeeewwwww** [comment]
![localhost_4001_agency-talent-portal_auth_reset-password-with-error_](https://user-images.githubusercontent.com/13023132/47523119-4d997800-d865-11e8-9008-b13c27d023a4.png)
@jonwoody Above is a screenshot I mocked up. I created a new layout that can be copied from, just made a pull request for that to the main design system branch, that'll be up when Matt gets a chance to clear it (and _if_ it is up to snuff).
