### ISSUE TITLE
Update content for 404 page for ATP - TFS 30640

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#31]
TFS Ticket 30640
BA - Jon Woody

Request: We need some wording for the body of the 404 page for ATP. We will be using the standardized 404 page design words that are in the design system. However for the “Head back… Go to… Begin Your…” we need to update it for ATP.

**Comment by dalenard21** [comment]
@jonwoody here's the content to use. THis is the same as what I sent to you in email.

* Head back to home. (where ‘home’ links to the ATP home page)
* Get answers to frequently asked questions. (this goes to the ATP faq page/support center)
* Contact us at Recruiter-Help@usajobs.gov (but make sure that Brody is okay having this email address available here)

**Comment by dalenard21** [comment]
@jonwoody did this get implemented in production?  If so, I'll close this issue out.

**Comment by jonwoody** [comment]
@dalenard21 Completed! I'll close out the github ticket.
