### ISSUE TITLE
Content for State program notifications (TFS 35787)

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#33]
First task is for @Piglady64: Please work with Drew and Bridget/Nora to determine and document how VSFS communicates status to applicants today. Michelle would like to mirror what they do in our communication. We may have screen shots of this on the google drive so I'd check there first. But, it may be something we need to revisit with Bridget and Nora (an email exchange should suffice).

Second task is for myself and @benjawin: Add notifications to our service blueprint for the State back-end.

Third task is for @dalenard21: Create content for any automatic notifications.

Fourth task is for @dalenard21 & @starrchen (now @dreeeeewwwww too): Code responsive email template for Open Opps communications with State "branding".

**Comment by Piglady64** [comment]
I sent an email to Bridget asking for all touchpoints with Students with the text for those communications. Will update once I hear from her. I just got an out of office so I may not get this information until next week.

**Comment by Piglady64** [comment]
Here is how VSFS communicates with Students.

We keep VSFS emails fresh each year but here’s an estimate on the touch points:

Students apply through USAJOBS – once we have their email addresses from HR’s Marvin Moore, we send a mass email that says their application made it through. This happens at the beginning of August. During the month of August, offices can send email offers out through the site.  Once a student accepts the offer, another email goes out that confirms acceptance. Then, VSFS sends out (not through the site) a “welcome to VSFS” email BCCing all accepted eInterns in early September. We then send an email (not through the site) in December and one again in the spring. The December one is usually a season’s greetings graphic and the spring one is about wrapping up work. 

I believe I HR at State has copies of the language we used a few years ago. Hope this helps!

**Comment by humancompanion** [comment]
Okay. So here are the emails I think need to be sent and whether they are sent automatically or not (spoiler alert: only the first one).

1. Application received - Automatic. Tells the applicant we've received their application and provides an outline of the process, next steps (someone will reach out to you for an interview).

2. Selected for interview. This template would give the bureau content that indicates that the applicant has been selected to be interviewed and suggest some possible interview times.

3. Offer. This template would give the bureau content that indicates that an offer has been extended to the applicant at this location. It would indicate important things like start date, travel, and next steps.

4. Background check. This template would give the bureau content to indicate to the applicant that they must now start their background investigation (I presume they use eQIP but, we should double check). 

5. You were not selected :-(  This template would give the bureau content to indicate to the applicant that they were not selected. Again, we should reach out to VSFS and see if they want us to offer their program up as an alternative.


#### Optional

If State is interested in giving those who didn't meet the min quals another option AND VSFS is interested in those folks then there may be a communication we'd send to those who were eliminated during the application process because they are A. Not a US Citizen or B. Do not have a GPA above. 3.0.

**Comment by humancompanion** [comment]
Going to evaluate their current communications and make a recommendation to tighten up the applicant accepting the offer before going off to eQIP.

**Comment by dalenard21** [comment]
Here is some sample content from State. 
[Mock Offer Letter to Candidates.docx](https://github.com/USAJOBS/ATP-Support/files/2695485/Mock.Offer.Letter.to.Candidates.docx)

**Comment by dalenard21** [comment]
Actively working on this as of 12/20.  Met with State yesterday and they clarified their communication more.

Need due date.

**Comment by dalenard21** [comment]
@dreeeeewwwww @Piglady64 @humancompanion @kbwagner 

Here's a first draft of the 'Application Received' automated email content.  Please review and provide feedback.

[Department-of-state-student-internship-program-application-received-email_20190104.docx](https://github.com/USAJOBS/ATP-Support/files/2728308/Department-of-state-student-internship-program-application-received-email_20190104.docx)

**Comment by dalenard21** [comment]
@Piglady64 @kbwagner @dreeeeewwwww @humancompanion 

Here's a first draft of the "You've been selected for an interview" email.  I have several comments/questions in the word doc.  

Have we decided if these emails will be signed as the "U.S. Department of State Student Internship Program (unpaid)" or as "Open Opportunities"?

@dreeeeewwwww how much of this can we 'templatize'?  I included spaces where the hiring manager can plug in the 'internship opportunity', the hiring office/bureau, the dates/times for an interview and the contact info for who the applicant needs to contact to confirm the date/time.  

DOS did not send an example of their current "interview' email. I'm not sure if they have one, or if their current process is to call people. So, we need to confirm this process with them and make sure the email has the right info/steps.

[Department-of-state-student-internship-program-selected-for-interview_20190107.docx](https://github.com/USAJOBS/ATP-Support/files/2734043/Department-of-state-student-internship-program-selected-for-interview_20190107.docx)

**Comment by humancompanion** [comment]
@dalenard21 - Feedback on Application received. Answers to your questions:

* We should send just one notification that contains all three opportunities that the student applied to. 
* Applicants can't, to my knowledge, update their application once submitted. However, I would expect that in future (if not today) the profile that a State Dept. person would see in ATP would be the current information in that user's USAJOBS Profile (not just a copy of what was submitted). I'd take out the line about making sure your info is up-to-date. 
* Why are we using the impersonal "Agency" here? Why not Department of State? Or how about just a context setting sentence at the top like "The Department of State will: 1. Review all applications. 2. Set up interviews. 3. Send confirmation email."?
* Why "Agency sends confirmation email"? It's more of an offer that they need to accept, no?

**Comment by kbwagner** [comment]
@dalenard21 I haven't fully read the emails but just saw the comments and wanted to provide a couple of details:
1) State is very insistent that their program be referred to as "U.S Department of State Student Internship Program (Unpaid)”  Any references to DOS must include the U.S. in front.
2) Per @humancompanion comment above - State does now want the ability for their applicant's to update the application once submitted as long as it's before the closing date.  I'm not sure we have fully designed this and @Piglady64 is going to check our meeting minutes to see the final decision.  I know it's discussed in a Github ticket somewhere but if that changes some of your text standby for an update.

Will try to get to read these today.

**Comment by dalenard21** [comment]
@humancompanion @Piglady64 @kbwagner 

Thanks for the feedback.  Here's an another version.  

The program name "U.S. Department of State Student Internship Program (Unpaid) is long and I'd prefer to not have to use it every time.  Can we say "They" or can we say "Internship program coordinator".  I'm not a huge fan of using "They".  I'd rather
[Department-of-state-student-internship-program-application-received-email_20190108.docx](https://github.com/USAJOBS/ATP-Support/files/2738090/Department-of-state-student-internship-program-application-received-email_20190108.docx)
 say "we", but only want to do that IF the emails are signed from the U.S. Department of State...

**Comment by humancompanion** [comment]
@dalenard21 - Works for me.

I would expect the emails to be signed from State. It's their program not ours. Also, VSFS emails should be signed from them and so on and so forth for other Communities. 

@kbwagner - I saw the research issue assigned to me to rethink the design given the new requirement to allow updates to a submitted application. I'll respond there.

**Comment by dalenard21** [comment]
@humancompanion @kbwagner @Piglady64 @dreeeeewwwww 

Here's version 2 of the "Selected for an interview" email.  As Matt suggested, I think this email can be partly 'templatized', but then also needs an area where the hiring manager/internship coordinator can fill in specific times/dates/info for the interviews.  @dreeeeewwwww 
[Department-of-state-student-internship-program-selected-for-interview_20190109.docx](https://github.com/USAJOBS/ATP-Support/files/2741840/Department-of-state-student-internship-program-selected-for-interview_20190109.docx)
Is that possible?

**Comment by humancompanion** [comment]
@dalenard21 - I believe this mock-up will answer your questions:
https://opm.invisionapp.com/d/main/#/console/10285286/336755995/preview

You and @dreeeeewwwww  should discuss the functionality so you are on the same page.

**Comment by dalenard21** [comment]
@humancompanion thanks.  

The only 'step' that we haven't really talked about having a message for is "Interviewed".  So, once an applicant is interviewed, and they get moved to this column...does that push out another message to them?  A "Thanks for interviewing" message?  I suppose this could be a message template that offers a text box that someone can write what they want - thank the applicant and perhaps tell them when they might hear about a decision, or if they have more questions?

@dreeeeewwwww let's talk about what makes most sense.

Right now, I have draft content for:

* Application received (posted earlier in this github issue)
* Selected for interview (posted earlier in this github issue)
* Not selected for internship (posted now in this comment)

@kbwagner @Piglady64 @humancompanion @dreeeeewwwww  please review the "Not selected for internship" content.  I edited the DOS existing "not selected' letter.  I THINK this could be a full template - where it's the same language for each applicant.  But, we'd need to run that by DOS.

[Department-of-state-student-internship-program-not-selected-email_20190110.docx](https://github.com/USAJOBS/ATP-Support/files/2746232/Department-of-state-student-internship-program-not-selected-email_20190110.docx)

**Comment by Piglady64** [comment]
@dalenard21 I have suggested a couple of edits. These are merely suggestions, do not feel like you have to make the changes.
[Department-of-state-student-internship-program-not-selected-email_20190110 with julies comments.docx](https://github.com/USAJOBS/ATP-Support/files/2765379/Department-of-state-student-internship-program-not-selected-email_20190110.with.julies.comments.docx)

**Comment by dreeeeewwwww** [comment]
A couple till some things I need to do to polish up the body content styling (maybe worth moving to a new issue):
- [ ] One
- [ ] Two
- [ ] Three

**Comment by humancompanion** [comment]
@dreeeeewwwww - Good stuff. This looks much improved. Two things I noticed:

1. We should link www.careers.state.gov in the Thanks for your interest email.
2. I wish there were some way to break up the name of the program from the title of the email. Perhaps the name of the program could be a bit smaller and separated a bit from the title?

**Comment by humancompanion** [comment]
Debbie to send Drew the footer content from Open Opps.
Drew to remove duplicative content in footer.

**Comment by dreeeeewwwww** [comment]
- [ ] Swap USAJOBS logo for Open Opps
- [ ] Clean up formatting on body text
- [ ] add new frontmatter param to break up program and email title

**Comment by dreeeeewwwww** [comment]
@humancompanion @dalenard21 

I updated the Dos repo card with HTML links and screenshots -> https://github.com/USAJOBS/DoS/issues/37#issuecomment-457751607

**Comment by dreeeeewwwww** [comment]
@dalenard21 I created a shell template for the "you've been selected for an internship" email that came up in this week's State meeting.

**Comment by dreeeeewwwww** [comment]
@humancompanion @dalenard21 @Piglady64 Closing this issue and [referencing it in **DoS #37**](https://github.com/USAJOBS/DoS/issues/37). It is generally a duplicate and the most recent updates have been made there.
