### ISSUE TITLE
ATP: State Unpaid Internship campaign template

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#34]
As a bureau chief selecting students for the unpaid internship program I need to have an organized workflow for managing applicants.

This will be achieved with a predefined set of lists in a Campaign in ATP. 

* [x] Define the required "states" (lists)
* [x] Depict a campaign pre-populated with lists.

This is the view in question**:
https://opm.invisionapp.com/d/main/#/console/10296658/329193724/preview

The MVP of this may be just a document that informs the State HQ folks how to set up their campaigns in ATP. A stretch goal would be us pre-populating the DB on their behalf.

(**Publicly viewable invision link: [https://opm.invisionapp.com/share/WYOESMSPNK5#/329193724_projects_Homepage](https://opm.invisionapp.com/share/WYOESMSPNK5#/329193724_projects_Homepage))

**Comment by humancompanion** [comment]
Proposed template of statuses:

* Assigned
* Interviewing
* Interviewed
* Offer out
* Accepted

**Comment by humancompanion** [comment]
As a bureau chief managing applicants to my internship I need a way to:

* [ ] Know who has been assigned to me (list named "Assigned")
* [ ] Indicate who I want to talk to (list named "Interviewing")
* [ ] Indicate who I talked to (list named "Interviewed")
* [ ] Indicate who I've extended an offer to (list named "Offer out")
* [ ] Indicate who has accepted an offer (list named "Accepted")

**Comment by dreeeeewwwww** [comment]
Default board view with defined lists to sort candidates:

![board-initial 2x](https://user-images.githubusercontent.com/13023132/49476742-d0a8d900-f7e8-11e8-9856-23ee6ec32ad8.png)

**Comment by humancompanion** [comment]
We saw this yesterday and it looked good to me. @dreeeeewwwww - Please move close this if you agree.
