### ISSUE TITLE
JOA Playbook: Release notes for v7.4

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#43]
* Add a new field to the SIF called Agency External Contact URL which will provide Agencies the ability to provide a URL as their external contact method.  This field is only to be used for online ticketing systems, and should not be used for general URLs
* Update the agency contact information section to display a third address line on the JOA  (Address fields 4 and 5 have been removed from the data dictionary)
* Make minor updates to the new user flow in USAJOBS
* Make Video display updates in the JOA improving the display on mobile and larger screen devices

**Comment by dalenard21** [comment]
@humancompanion I added the 7.4 release notes.  Looks fine in federalist.

https://federalist-proxy.app.cloud.gov/site/usajobs/atp-support/job-announcement-playbook/release-notes/

This is ready to go out with the 7.4 release.  

Closing issue.
