### ISSUE TITLE
Update help text for PIV sign in

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#52]
@abudz19 is working on TFS ticket 35415

Need to update the help text under the PIV sign in area to be more helpful

Something along the lines of:

Have you registered your PIV?
You will need your Agency Talent Portal email and password to associate your PIV card with your account. Login with just your PIV and PIN number after registering.

link to atp: http://agencyportal.usajobs.gov/

**Comment by dalenard21** [comment]
@abudz19 what step do they need to take to register their PIV?  I see they need their ATP email and password...but is there a link?  What happens when they click on the PIV card and they haven't registered it yet?  When I click on it, I get the "Something isn't working".

**Comment by dalenard21** [comment]
@abudz19 let's try this:

Replace "Need to register your PIV card?"

with

Want to use your PIV card?
You can sign in with your PIV card, but first you need to register it. You'll need your Agency Talent Portal email and password to register your card.

make 'register your card' a link to where the user can actually register their card.

**Comment by dalenard21** [comment]
Hi @abudz19 can this be closed?

**Comment by abudz19** [comment]
It is requirements ready, so let's close.
