### ISSUE TITLE
Access denied email - need content

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#56]
TFS Ticket 35057

As a potential user, I want an email sent to me confirming that my account was denied.

An agency admin/recruiter help can deny access to ATP.  If that happens, the user/requester will get an email stating their access was denied.

**Comment by dalenard21** [comment]
@abudz19 here's the first draft for the 'access denied' email.  I wasn't sure whether we can direct users to their agency admin or back to recruiter help if they want to ask why they were denied.  Please review and let me know if any changes are needed.  
[ATP-access-denied-email_20190103.docx](https://github.com/USAJOBS/ATP-Support/files/2725091/ATP-access-denied-email_20190103.docx)

**Comment by abudz19** [comment]
@dalenard21 For this ticket, we want to direct users back to their agency admin (or in the event that one is not assigned, Recruiter-help). Brody confirmed that we can include the agency admin's direct contact in the email, since this new process is trying to eliminate Recruiter-help as the middleman.

**Comment by dalenard21** [comment]
@abudz19 I've attached an updated version to include the agency admin contact info and another message if there is not agency admin, to contact recruiter-help.  My thinking is, if there IS an agency admin, only include their information and not recruiter-help.  If there is NO agency admin, include message to contact recruiter-help.

Thoughts?
[ATP-access-denied-email_v2_20190104.docx](https://github.com/USAJOBS/ATP-Support/files/2727597/ATP-access-denied-email_v2_20190104.docx)
