### ISSUE TITLE
Choose icon for Review tab in main navigation

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#60]
Dev has moved forward with placing the link to the campaign review index in the main navigation. The nav item appears conditionally based on your status as an applicant reviewer for DOS internships.

- [x] Choose a font awesome icon that represents `Review`/`Applicant review`

* Connected to #59

**Comment by dreeeeewwwww** [comment]
A few quick ideas from scanning Font Awesome:

- [File signature](https://fontawesome.com/icons/file-signature?style=solid)
- [File contract](https://fontawesome.com/icons/file-contract?style=solid)
- [Highlighter](https://fontawesome.com/icons/highlighter?style=solid)
- [Stamp](https://fontawesome.com/icons/stamp?style=solid)

**Comment by dreeeeewwwww** [comment]
`Columns` seems to be the most literal here, since you're going to card/column view in the end.

`Stamp` maybe comes second for me, since the process is for reviewing/approving.

**Comment by dreeeeewwwww** [comment]
O! Also I forgot I had also put [list-alt](https://fontawesome.com/icons/list-alt?style=regular) in as a placeholder in Invision awhile back. That also could be a good option (current version online seems to be slightly different than the font file on my computer).

https://opm.invisionapp.com/share/Q8OESMCYS5P#/343752173_Nav_-_Applicant_Review

**Comment by dreeeeewwwww** [comment]
@humancompanion added the `columns` icon after talking yesterday.

https://opm.invisionapp.com/share/Q8OESMCYS5P#/343752173_Nav_-_Applicant_Review

**Comment by humancompanion** [comment]
Looks fine. Continue to include that in your symbols in Sketch. You can update the shared library file as well if that helps. 

Let's close this and move onto actually fixing the navigation properly.
