### ISSUE TITLE
JOA Playbook: Add new security fields

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#65]
The JOA is getting a couple of new fields for 'Security Clearance'.

1. Trust determination process

* Credentialing
* Suitability/fitness
* National security

1. Position sensitivity and risk

* Non-sensitive/Low Risk
* Non-sensitive/Moderate Risk
* Non-sensitive/High Risk
* Noncritical-Sensitive/Moderate Risk
* Noncritical-Sensitive/High Risk
* Critical-Sensitive/High Risk
* Special-Sensitive/High Risk

We need to add these fields and their values to the JOA Playbook.

**Comment by dalenard21** [comment]
@humancompanion here's a draft of the update to the JOA playbook for the new security fields.  I emailed Charles Drennan asking to review and provide descriptions of the different levels.  Waiting to hear back.  However, I'll update the page with what I have for now.
[JOA-playbook-background-check-security-clearance_20190219.docx](https://github.com/USAJOBS/ATP-Support/files/2881263/JOA-playbook-background-check-security-clearance_20190219.docx)

**Comment by humancompanion** [comment]
Deployed.
