### ISSUE TITLE
ATP: New user email - Access confirmation [TFS 35058]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#69]
## From TFS

As a new user, I want an email that confirms I was granted access to ATP.

When a user has been granted access to ATP, the following email is sent. This email comes from agency admin or recruiter help and includes a message telling the user they have access to ATP:

**Email subject line:**
```
Welcome to the USAJOBS Agency Talent Portal
```

**Email content:**
```
Hello [User name],

Welcome to the USAJOBS Agency Talent Portal (ATP). With an ATP account you can:

- Search resumes and find qualified job seekers.
- Create campaigns to share lists of job seekers to review and manage with your recruitment team.
- Create recruiting events to post on USAJOBS.

<Sign into the USAJOBS Agency Talent Portal>(link to ATP sign in page).

Thanks,
The USAJOBS Agency Talent Portal Team
```

**Comment by KatMullens-work** [comment]
Link to this item's TFS issue: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35058

As of 2/6/19, per Drew there is not a design for this item yet.

**Comment by dalenard21** [comment]
@dreeeeewwwww - yes, the content is correct.  I've attached the original word doc.
[ATP-access-granted-email_20190103.docx](https://github.com/USAJOBS/ATP-Support/files/2841535/ATP-access-granted-email_20190103.docx)

**Comment by KatMullens-work** [comment]
Updated AC:

When a user has been granted access to ATP, the following email is sent. This email comes from agency admin or recruiter help (depending on who approved it) and includes a message telling the user they have access to ATP:

Email subject line: Welcome to the USAJOBS Agency Talent Portal
Email content:
Hello [User name],

Welcome to the USAJOBS Agency Talent Portal (ATP). With an ATP account you can:
·       Search resumes and find qualified job seekers.
     Create campaigns to share lists of job seekers to review and manage with your recruitment team.
     Create recruiting events to post on USAJOBS.
<Sign into the USAJOBS Agency Talent Portal>(link to ATP sign in page).

Thanks,
The USAJOBS Agency Talent Portal Team

**Comment by dalenard21** [comment]
@Piglady64 FYI.

**Comment by dalenard21** [comment]
Per @jdstill on slack, this issue can be closed.
