### ISSUE TITLE
ATP: New user email - Deny confirmation [TFS 35057]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#70]
## From TFS

As a potential user, I want an email sent to me confirming that my account was denied.

As a potential user,  if my account request was denied, I want an email sent to me confirming that my account was denied containing the following:

**Email subject line:** 
```
Your USAJOBS ATP request was not approved
```

**Email content:**

```
Hello [User name],

Thanks for your interest in the USAJOBS Agency Talent Portal.  Unfortunately, we can’t approve your request for an ATP account.  Please contact your agency administrator below for more information.

Your agency administrator: <insert agency contact information>

<If no agency admin, insert message “Your agency does not have an administrator for ATP. Please contact recruiter-help@usajobs.gov for more information.”>

Thanks,
The USAJOBS Agency Talent Portal Team
```

**Comment by KatMullens-work** [comment]
Link to this item's TFS issue: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35057

As of 2/6/19, per Drew there is not a design for this item yet.

**Comment by dalenard21** [comment]
@dreeeeewwwww - yes, this content is correct. I've attached the original word doc
[ATP-access-denied-email_v2_20190104.docx](https://github.com/USAJOBS/ATP-Support/files/2841528/ATP-access-denied-email_v2_20190104.docx)

**Comment by KatMullens-work** [comment]
Updated AC: 
As a potential user,  if my account request was denied, I want an email sent to me confirming that my account was denied containing the following:

Email subject line:  Your USAJOBS ATP request was not approved
Email content:
Hello [User name],

Thanks for your interest in the USAJOBS Agency Talent Portal (ATP).  Unfortunately, we can’t approve your request for an ATP account.  Please contact your agency administrator below for more information.

Your agency administrator: <insert agency contact information>
<If no agency admin, insert message “Your agency does not have an administrator for ATP. Please contact recruiter-help@usajobs.gov for more information.”>

Thanks,

The USAJOBS Agency Talent Portal Team

**Comment by dalenard21** [comment]
@Piglady64 FYI.

**Comment by dalenard21** [comment]
Per @jdstill on slack, this issue can be closed.
