### ISSUE TITLE
ATP: New user email - email validation [TFS 35055]

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#72]
## From TFS

As a potential user, I want an email sent to the email address that I register with so that my control of the email account can be validated.

Following the process in outlined in ticket 35054. 

- This email is sent once a user submits a new user form in ATP. 
- The email contains a button / link to confirm the information.
- An email is sent to the user containing the following text: 

**Email subject line:**
```
Please confirm your email address.
```

**Content from TFS:**

```
Email content:

Hello [User name],

Thanks for your interest in the USAJOBS Agency Talent Portal.  Click the button below or copy and paste the entire link into your browser to confirm your email address.  Once you confirm your email address, your agency administrator will review your request and you’ll receive another email if your account is approved.

<button/link label “Confirm your email address”>

<include full URL so someone can paste into their browser instead>

This link will expire in 24 hours.

Thanks,

The USAJOBS Agency Talent Portal Team
```

**Comment by KatMullens-work** [comment]
As of 2/6/19, no designs are available for this ticket. 

Link to this job's TFS ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems/edit/35055

**Comment by KatMullens-work** [comment]
Updated AC:

- This email is sent once a user submits a new user form in ATP. 
- Once a user submits their new user form, an email is sent to the user to validate the information and to validate control of that email address. 
-This email contains a button/link to confirm the information. 
- If the button/link is clicked, it triggers an account validation email to be sent to an agency admin (if one exists for the agency selected on the user form) or  
if no agency admin exists for that agency, the form will be sent to Recruiter-Help@usajobs.gov.
- If that link is not clicked, no action is taken on the ATP side.

- The email contains a button / link to confirm the information.
- An email is sent to the user containing the following text: 

Email subject line: Please confirm your email address.
Email content:
Hello [User name],

Thanks for your interest in the USAJOBS Agency Talent Portal (ATP).  Click the button below or copy and paste the entire link into your browser to confirm your email address.  Once you confirm your email address, your agency administrator will review your request and you’ll receive another email if your account is approved.

<button/link label “Confirm your email address”>

<include full URL so someone can paste into their browser instead>

This link will expire in 24 hours.

Thanks,
The USAJOBS Agency Talent Portal Team

**Comment by dalenard21** [comment]
@Piglady64 FYI.  Not sure what the status is here.

**Comment by dalenard21** [comment]
Per @jdstill on slack, this issue can be closed.
