### ISSUE TITLE
Messaging: Alerts for send success/fail 

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#74]
We need to alert applicant reviewers about the send status of a message. Applies to individual and group messages.

- [x] Success!
- [x] Fail!
- [ ] ~~Validation on missing fields (if applicable)~~

Modal styling: https://usajobs.github.io/design-system/modals/

**Comment by dreeeeewwwww** [comment]
@dalenard21 I have some basic alert modals mocked up to show success/failure of a message send and need your help on the copy for inside the modal body.

-----

**Message send success**

https://opm.invisionapp.com/share/Q8OESMCYS5P#/349391482_Internship-Board-Message_Individual_-_Success

-----

**Message send failure**

https://opm.invisionapp.com/share/Q8OESMCYS5P#/349391507_Internship-Board-Message_Individual_-_Error

I'm not sure of the exact circumstances that a message wouldn't send, so I'm guessing a blanket statement about how something went wrong would cover most of our bases to start.

**Comment by dalenard21** [comment]
@dreeeeewwwww sorry for the delay in getting this to you.

For success message, I think just sway, to emphasize the success:

Heading: Message sent
Body: Your message was sent successfully.

For failure message:
Heading: Message not sent
Body: Your message failed to send.

Thoughts?

**Comment by dalenard21** [comment]
@dreeeeewwwww do you need anything else from me on this?

**Comment by dreeeeewwwww** [comment]
**Success**

https://opm.invisionapp.com/share/Q8OESMCYS5P#/349391482_Internship-Board-Message_Individual_-_Success

I updated the body of the success message to include the same template/recipient info that displays in the send message panel.

**Fail**

https://opm.invisionapp.com/share/Q8OESMCYS5P#/349391507_Internship-Board-Message_Individual_-_Error

**Comment by humancompanion** [comment]
Not yet filed as a TFS ticket.

**Comment by dalenard21** [comment]
@jdstill - I have this GitHub issue in my backlog and I honestly don't know if this has been developed, if it's a TFS ticket, or if there was a decision to not have these alerts.

Do you know anything about this?

**Comment by dalenard21** [comment]
Per @jdstill on Slack: "We did the success message in ticket https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_workitems?id=36974&_a=edit&triage=false.  I don't think we were ever able to determine way a message would not send so the Fail message was never done."

Issue closed.
