### ISSUE TITLE
Email - Invite new user email (TFS 36343)

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#77]
From Jon W. There is a TFS ticket to create a page in ATP where a privileged user can invite a federal employee to become an ATP user. The invitor will enter the invitee’s federal email address, role and agency into the Invite User ATP page, which will trigger an email to be sent to the invitee to accept and complete their account setup process. 

Definition: “Privileged User” – any ATP user with a role that allows them to manage other users. (For example, Agency Admins, PMO.)

Per Brody, he would like the following information in the email template:

-Email includes a custom URL to send the invitee to ATP [URL not defined yet]
-Relevant body of text stating the invitee is invited to be a user in ATP and to use the (above) URL to complete your account setup process. 

@dreeeeewwwww I assume this might need to be mocked up?  Or accounted for in the ATP flow?

I've attached the content.
[ATP-invite-user-email_20190207.docx](https://github.com/USAJOBS/ATP-Support/files/2841487/ATP-invite-user-email_20190207.docx)

**Comment by dreeeeewwwww** [comment]
@dalenard21 Brody just brought this one up in the planning meeting. Looks like the plan is to just send this as text for now, as it will match existing, similar messages.

Down the line, the idea would be to make it (and all other messages) responsive HTML emails.

**Comment by dreeeeewwwww** [comment]
Closing this as it will be sent as text, matching existing ATP email communications.
