### ISSUE TITLE
ATP: VSFS variation of initial campaign lists

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#80]
@dreeeeewwwww - For Thursday's meeting with VSFS at 1pm we need to depict two changes in ATP mocks:

1. Showing an initial board where the first list is not named "Assigned". They had a strong negative reaction to this label. They wanted "First choice", "Second choice", etc. However...
2. Show the applicant's preferences (3 choices) somewhere either in the card or in their Profile panel. If we have this then we shouldn't need multiple initial "choice" lists. Instead we could perhaps rename that first list "For review" or "Incoming" or...? I leave it to you (reach out to Julie or Debbie if you need help).

**Comment by Piglady64** [comment]
@humancompanion the VSFS meeting is at 11:15 our standing Unpaid meeting is at 1 tomorrow

**Comment by dreeeeewwwww** [comment]
https://opm.invisionapp.com/share/Q8OESMCYS5P#/346704495_Internship-Board-Small_Cards-VSFS

- [ ] Changed `Assigned` to `For review`
- [ ] 3 choices are already noted in the applicant preview modal

**Comment by dreeeeewwwww** [comment]
Closing, VSFS won't be using ATP for upcoming release.
