### ISSUE TITLE
ON HOLD - (Woody needs to edit ticket) ATP: New User - Account Pending Page (TFS 36392)

### ISSUE THREAD

**Issue by jonwoody** [USAJOBS/ATP-Support#81]
Need text to display on page. The gist of this page is a landing page where once a person opens an email that instructs the person to click on a link to confirm their email address, the person will be directed to this account pending page. This page should indicate that the person's email is confirmed and that their account authorization is now pending.

**Comment by dalenard21** [comment]
@jonwoody is this still ON HOLD?

**Comment by dalenard21** [comment]
@abudz19 created a new issue for this in the design repo.  Closing this issue.
