### ISSUE TITLE
JOA Playbook: Prepare release notes for v7.6

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/ATP-Support#85]
Let's get the notes from John and prep for the v7.6 release.

**Comment by dalenard21** [comment]
messaged John.

**Comment by Piglady64** [comment]
@dalenard21 I got an out of office from John this morning. He is out today but should be back tomorrow

**Comment by dalenard21** [comment]
As of 2/22/19 John is still working on the release notes for 7.5 and 7.6 and will send over when they're ready.

**Comment by dalenard21** [comment]
@humancompanion and @dreeeeewwwww I updated the playbook with both 7.5 and 7.6.  I 'included' them both on the index page...but I'm not sure if they'll show up correctly, so you may want to check that.

**Comment by humancompanion** [comment]
Deployed.
