### ISSUE TITLE
ATP: Existing Account Alert (TFS 36395)

### ISSUE THREAD

**Issue by jonwoody** [USAJOBS/ATP-Support#86]
Need text presented in an alert within ATP.

When privileged user submits ATP user invitation, the email address should be validated to ensure it does not already exist in ATP.

If invitee email exits in ATP database, then an alert banner will appear at top of page stating the something similar to the following: "This account cannot be created as [email address being invited] has an existing account attributed to [insert associated ATP agency to invitee email address]. Please contact USAJOBS people if you need further assistance."

Need better wording for the last sentence that includes a mailto link to an appropriate person/email for assistance.

**Comment by dalenard21** [comment]
Hi @jonwoody 

How about this:

Heading: Account already exists
Text: "Looks like <enter email address> is already associated with an ATP account. Please enter a different email address or contact us."

I'm not sure who the 'contact us' should be?  Is it recruiter-help@usajobs.gov?  If so it could say:

...contact us at recruiter-help@usajobs.gov

Let me know if there's anything else.

**Comment by jonwoody** [comment]
Looks good. We'll go with:

Heading: Account already exists
Text: "Looks like is already associated with an ATP account. Please enter a different email address or contact us at [recruiter-help@usajobs.gov](mailto:recruiter-help@usajobs.gov)."

**Comment by Piglady64** [comment]
@jonwoody @dalenard21 Is there something missing here? "Looks like is..." That doesn't make sense. Will the email be put here? Will it say "Looks like this email is already associated...." I don't see the usual ,<insert email>. Just don't want to put it in the A/C like this.

**Comment by dalenard21** [comment]
@Piglady64 @jonwoody 

Oh yes, sorry it must not have copied over from my word document.  It should be:

"Looks like [insert email address] is already associated with an ATP account.  Please enter a different email address or contact us at [recruiter-help@usajobs.gov](mailto:recruiter-help@usajobs.gov)."

**Comment by dalenard21** [comment]
@jonwoody @Piglady64 we had lots of convo on Slack about this GitHub issue, so I'm just adding the agreed upon text here, so we're all on the same page.

Here's what we settled on for the 'alert':

"[insert email address] already has an ATP account with [insert agency name]. Please contact the Agency Admin or us at recruiter-help@usajobs.gov to add them to your agency."

Placement - there was some back and forth about where to display the message.  @jonwoody do you know if the email address field is being validated when a user exits that field OR when the user hits 'invite' (after they've filled out the other two fields)?  If it happens automatically when a user exits the field, then it makes sense.  But if it's after they hit 'invite', it makes more sense to display the alert at the top.

I know it's too late to change now, but might want to get this into the backlog.

**Comment by dalenard21** [comment]
@jonwoody what's the status on this github issue?  Can I close it?

**Comment by dalenard21** [comment]
@jonwoody any update?

**Comment by dalenard21** [comment]
@Piglady64 again, not sure where we landed on this one or if it's been updated.

**Comment by dalenard21** [comment]
@jonwoody is there an update on TFS 36395?  Can I close this issue?

**Comment by dalenard21** [comment]
TFS ticket is closed.  Closing this issue.
