### ISSUE TITLE
ATP new user and login process - login.gov

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#87]
**Collecting all the issues for the new ATP login process.**

-----

Most recent diagram from Brody (2/15):

![new auth-user process](https://user-images.githubusercontent.com/13023132/53047556-a9b18900-3460-11e9-9f5b-2e29bbeab93e.png)

**Comment by brodydittemore** [comment]
Latest versions can be found at https://github.com/USAJOBS/ATP-PO/tree/master/documents

**Comment by dreeeeewwwww** [comment]
Outlined some basics of the process today with @humancompanion. Prelim sketch below copied from stickies (red dots denote new design work):

![login-gov-prelim-flow](https://user-images.githubusercontent.com/13023132/53765696-bdb4ac00-3e9e-11e9-8ab4-2e955dde6af0.png)

**Comment by dalenard21** [comment]
@Piglady64  no idea where thsi stands right now.  Just an FYI.

**Comment by humancompanion** [comment]
@dalenard21 and @Piglady64 - I'm picking this work up now at Brody's request. My goal is to update the mocks Drew stubbed at by tomorrow: https://opm.invisionapp.com/d/main/#/projects/prototypes/17190930

I'll then iterate on it next week. From there I will hand it to Alex as I will be in The Lab the week of 5/20. Alex will see it through to the end.

**Comment by dalenard21** [comment]
Closing this issue because users can now use their PIV, USA Staffing account or login.gov to sign in.

**Comment by dalenard21** [comment]
Closing this issue because users can now use their PIV, USA Staffing account or login.gov to sign in.
