### ISSUE TITLE
ATP - Update language on ATP authentication sign in page (TFS 36462)

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/ATP-Support#97]
The text "Need an account? Contact your agency administrator or email recruiter-help@usajobs.gov" will be changed to: "[[Click here]] if you've received a new user invitation, or contact your agency administrator or email recruiter-help@usajobs.gov.

Tweak this so it doesn't say "Click here".

Follow up with Sean.

**Comment by dalenard21** [comment]
After working with Julie, came up with this instead:

Did you get an email inviting you to create a new account in ATP?  If so, [create your ATP account here](link to page to create an account).

Might even be okay to remove 'ATP' and just say new account.  Need to see what the screen looks like.

**Comment by humancompanion** [comment]
@dreeeeewwwww to discuss our "make it like github" model with Sean and Marshall.

**Comment by dalenard21** [comment]
Closing this issue, because the ticket was removed from TFS.
