### ISSUE TITLE
Board: remove/reshuffle unneeded items in header

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/ATP-Support#99]
After talking with @jonwoody about BA/dev feedback after initial development, the "attached" opportunities section of the header isn't super relevant to internships as there is only _one_ opportunity attached. The header title links to the opportunity as well, so the "view opportunity" text/link isn't needed as well.

- [ ] Remove small linked opportunity text/link/icon/etc
- [ ] Move the `00 Seats` number to somewhere else in the header

**Comment by jonwoody** [comment]
Reminder - to also remove the seat counts in the column headers

**Comment by dreeeeewwwww** [comment]
@jonwoody After talking earlier today, I'm moving this to closed. If we get some crazy pushback for removing the ticket, you can send dev to me and Matt.
